//About List constant type
export const ABOUT_LIST_REQUEST = 'ABOUT_LIST_REQUEST'
export const ABOUT_LIST_SUCCESS = 'ABOUT_LIST_SUCCESS'
export const ABOUT_LIST_FAIL = 'ABOUT_LIST_FAIL'

// ABOUT List Details constant type
export const ABOUT_DETAILS_REQUEST = 'ABOUT_DETAILS_REQUEST'
export const ABOUT_DETAILS_SUCCESS = 'ABOUT_DETAILS_SUCCESS'
export const ABOUT_DETAILS_FAIL = 'ABOUT_DETAILS_FAIL'

export const ABOUT_DELETE_REQUEST = 'ABOUT_DELETE_REQUEST'
export const ABOUT_DELETE_SUCCESS = 'ABOUT_DELETE_SUCCESS'
export const ABOUT_DELETE_FAIL = 'ABOUT_DELETE_FAIL'

export const ABOUT_CREATE_REQUEST = 'ABOUT_CREATE_REQUEST'
export const ABOUT_CREATE_SUCCESS = 'ABOUT_CREATE_SUCCESS'
export const ABOUT_CREATE_FAIL = 'ABOUT_CREATE_FAIL'
export const ABOUT_CREATE_RESET = 'ABOUT_CREATE_RESET'

export const ABOUT_UPDATE_REQUEST = 'ABOUT_UPDATE_REQUEST'
export const ABOUT_UPDATE_SUCCESS = 'ABOUT_UPDATE_SUCCESS'
export const ABOUT_UPDATE_FAIL = 'ABOUT_UPDATE_FAIL'
export const ABOUT_UPDATE_RESET = 'ABOUT_UPDATE_RESET'

export const ABOUT_HOME_REQUEST = 'ABOUT_HOME_REQUEST'
export const ABOUT_HOME_SUCCESS = 'ABOUT_HOME_SUCCESS'
export const ABOUT_HOME_FAIL = 'ABOUT_HOME_FAIL'
